###############################################################################
# Makefile for a script (e.g. Python) Assembler project
# Students:
# Oren Sultan, ID 201557972, oren.sultan@mail.huji.ac.il
# Shiran Aziz, ID 304813520, shiran.aziz@mail.huji.ac.il
===============================================================================



all:
	chmod a+x Assembler  Assembler.py Parser.py SymbolTable.py Code.py
